import Login from "@/components/auth/form-login";
// import { GithubButton } from "@/components/auth/social-button";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

const login = () => {
  return (
    <>
      <Login />
    </>
  );
};

export default login;
