import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const AuthLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <SessionProvider>
      <div>{children}</div>
      <Toaster />
    </SessionProvider>
  );
};

export default AuthLayout;
